# fly.toml app configuration file generated for dante-n8n on 2025-07-04T11:00:42+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dante-n8n'
primary_region = 'nrt'

[build]

[env]
  GENERIC_TIMEZONE = 'Asia/Seoul'
  N8N_BASIC_AUTH_ACTIVE = 'false'
  N8N_DIAGNOSTICS_ENABLED = 'false'
  N8N_HIRING_BANNER_ENABLED = 'false'
  N8N_LOG_LEVEL = 'info'
  N8N_USER_MANAGEMENT_DISABLED = 'false'
  TINI_SUBREAPER = 'true'
  TZ = 'Asia/Seoul'

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
